plugins:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "coverage/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/MethodLength:
  Max: 40
  Exclude:
    - "lib/fastlane/plugin/*/actions/*.rb"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "lib/fastlane/plugin/*/actions/*.rb"

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Max: 140

Naming/PredicateName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false
